### ISSUE TITLE
Way to generate audio for all preexisting flashcards?

### ISSUE THREAD

**Issue by Wyzmic** [themoeway/local-audio-yomichan#24]
I'm not sure if it's possible or not but it would be really neat if there was a way to regenerate the audio for all of my flashcards in one click.

**Comment by sammy-snipes** [comment]
theres an anki addon for generating batched audio https://github.com/DillonWall/generate-batch-audio-anki-addon

**Comment by Wyzmic** [comment]
That's exactly what I was looking for, thanks man! I tried to use it with the local audio server, but it doesn't work, think there's a way to make it work?
